export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
export const SUCCESS_PRODUCTS = "SUCCESS_PRODUCTS";

export const SET_PRODUCT_NAME = "SET_PRODUCT_NAME";
export const SET_PRODUCT_PRICE = "SET_PRODUCT_PRICE";
export const SET_PRODUCT_DESCRIPTION = "SET_PRODUCT_DESCRIPTION";
export const SET_PRODUCT_BARCODE = "SET_PRODUCT_BARCODE";
export const SET_PRODUCT_IMAGE = "SET_PRODUCT_IMAGE";
export const SET_PRODUCT_ID = "SET_PRODUCT_ID";

export const CLEAR_FORM_FIELDS = "CLEAR_FORM_FIELDS";
export const MODIFY_FORM_FIELDS = "MODIFY_FORM_FIELDS";

export const SET_SELECTED_ITEM = "SET_SELECTED_ITEM";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const SUCCESS_ADDED_PRODUCT = "SUCCESS_ADDED_PRODUCT";
export const ERROR_ADDED_PRODUCT = "ERROR_ADDED_PRODUCT";

export const ERROR_UPDATE_PRODUCT = "ERROR_UPDATE_PRODUCT";
export const SUCCESS_UPDATE_PRODUCT = "SUCCESS_UPDATE_PRODUCT";
