import { StyleSheet, Dimensions } from "react-native";
import colors from "../config/colors";

export const externalStyle = {
  wrapper: {
    paddingLeft: 20,
    paddingRight: 20,
  },
  container: {
    height: "100%",
    backgroundColor: "white",
  },
  semibold17: {
    fontFamily: "semibold",
    fontSize: 17,
  },
  greeting: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 25,
    marginHorizontal: 10,
  },
  semibold23: {
    fontFamily: "semibold",
    fontSize: 17,
  },
  homeCard: {
    marginBottom: 20,
    padding: 15,
    borderRadius: 8,
    height: 190,
  },
  homeTitle: {
    paddingTop: 4,
    marginLeft: 5,
    fontSize: 17,
    fontFamily: "semibold",
    color: colors.black,
  },
  homeCardHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  homeDescription: {
    color: colors.black,
    flexDirection: "row",
  },
  homeDescriptionItem: {
    color: colors.black,
    fontSize: 13,
    fontFamily: "regular",
    flex: 1,
    marginBottom: 4,
    lineHeight: 20,
  },
  headerButton: {
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.gray,
    backgroundColor: colors.black,
  },
  headerButtonText: {
    fontFamily: "regular",
    paddingVertical: 5,
    color: "white",
    marginTop: 2,
    fontSize: 13,
    paddingHorizontal: 15,
  },
  lgImage: {
    borderRadius: 8,
    // aspectRatio: 16 / 9,
    backgroundColor: colors.gray,
    width: "100%",
    height: 200,
  },
  regular13: {
    fontFamily: "regular",
    // color: colors.black,
  },
  priceBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    paddingVertical: 4,
    paddingTop: 6,
    paddingHorizontal: 10,
    backgroundColor: colors.black,
    borderRadius: 8,
    color: "white",
    fontSize: 15,
    fontFamily: "semibold",
  },
  nameBadge: {
    fontSize: 15,
    bottom: 10,
    position: "absolute",
    backgroundColor: "white",
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 8,
    left: 10,
    fontFamily: "semibold",
  },
  descriptionButton: {
    position: "absolute",
    top: 50,
    right: 10,
    paddingHorizontal: 10,
    backgroundColor: colors.gray,
    color: "white",
    borderRadius: 8,
    fontSize: 15,
    fontFamily: "semibold",
  },
  descriptionButtonText: {
    paddingVertical: 4,
    paddingTop: 6,
    color: "white",
    fontFamily: "regular",
  },

  scanWrapper: {
    padding: 5,
    zIndex: 5,
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  scanButton: {
    borderWidth: 2,
    borderColor: colors.gray,
    borderRadius: 8,
    backgroundColor: colors.black,
  },
  scanButtonText: {
    padding: 10,
    paddingHorizontal: 20,
    fontFamily: "semibold",
    color: "white",
  },
  noImage: {
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    // aspectRatio: 16 / 9,
    backgroundColor: colors.lightgray,
    width: "100%",
    height: 200,
  },
  scanDescription: {
    top: 0,
    left: 0,
    width: "100%",
    height: 200,
    position: "absolute",
    padding: 10,
    zIndex: 15,
    backgroundColor: colors.black,
    borderRadius: 8,
  },
  closeBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: colors.black,
    borderRadius: 8,
    color: "white",
    fontFamily: "semibold",
  },
  closeBtnText: {
    color: "white",
    fontFamily: "semibold",
    padding: 4,
    paddingHorizontal: 10,
  },
  inputField: {
    padding: 8,
    fontFamily: "regular",
    borderRadius: 8,
    paddingHorizontal: 15,
    backgroundColor: colors.lightgray,
  },
  searchIcons: {
    width: 40,
    height: 40,
    position: "absolute",
    right: 5,
    alignItems: "center",
    justifyContent: "center",
    top: 2,
  },
  smImage: {
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    width: 70,
    overflow: "hidden",
    backgroundColor: colors.lightgray,
    aspectRatio: 1 / 1,
    marginRight: 10,
  },
  productCard: {
    paddingVertical: 15,
    marginHorizontal: 20,
    flexDirection: "row",
  },
  label: {
    paddingVertical: 10,
    fontFamily: "regular",
  },
  imageUpload: {
    // marginVertical: 4,
    borderRadius: 8,
    borderStyle: "dashed",
    borderColor: colors.gray,
    borderWidth: 1,
    backgroundColor: colors.lightgray,
    // padding: 10,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    aspectRatio: 16 / 9,
  },
  barcodeBtn: {
    position: "absolute",
    top: 0,
    padding: 10,
    right: 5,
  },
  // description: {
  //   fontFamily: "regular",
  //   marginVertical: 8,
  // },
  // // end of inventory card
  // button: {
  //   marginTop: 10,
  //   padding: 12,
  //   borderRadius: 8,
  //   backgroundColor: colors.black,
  //   color: "white",
  //   fontFamily: "regular",
  // },
  // buttonText: {
  //   color: "white",
  //   textAlign: "center",
  // },
  // // end of download upload button

  // icons: {
  //   height: 24,
  //   width: 24,
  // },
  // card: {
  //   marginBottom: 20,
  //   padding: 15,
  //   borderRadius: 8,
  //   height: 190,
  // },

  //
  // // end of home card
  // credits: {
  //   marginTop: 10,
  //   fontFamily: "regular",
  //   fontSize: 12,
  //   color: "white",
  //   textAlign: "center",
  // },
  // footer: {
  //   marginTop: 20,
  //   alignItems: "center",
  //   // flexDirection: "row",
  //   justifyContent: "center",
  //   padding: 30,
  //   backgroundColor: colors.black,
  // },
  // // end of footer

  // header_style: {
  //   fontFamily: "semibold",
  //   fontSize: 17,
  // },
  // // end of header
  // text1: {
  //   fontFamily: "semibold",
  //   fontSize: 17,
  // },
  // text2: {
  //   fontFamily: "semibold",
  //   fontSize: 23,
  // },

  // dayImage: {
  //   width: 55,
  //   height: 55,
  // },
  // // end of greeting
  // logo: {
  //   height: 30,
  //   width: 30,
  // },
  // homeHeader: {
  //   // backgroundColor: "red",
  //   justifyContent: "center",
  //   alignItems: "center",
  //   flexDirection: "row",
  //   // width: "95%",
  //   // height: "100%",
  // },
  // // end of homeheaderleft
  // searchIcon: {
  //   position: "absolute",
  //   left: 15,
  //   top: 12,
  // },
  // searchbar: {
  //   padding: 10,
  //   paddingLeft: 50,
  //   paddingRight: 50,
  //   marginBottom: 10,
  //   borderRadius: 8,
  //   width: "100%",
  //   borderColor: colors.black,
  //   borderWidth: 1,
  // },
  // clearButton: {
  //   width: 40,
  //   height: 40,
  //   // backgroundColor: "red",
  //   position: "absolute",
  //   right: 5,
  //   alignItems: "center",
  //   justifyContent: "center",
  //   top: 5,
  // },
  // clearButtonImage: {
  //   width: 10,
  //   height: 10,
  // },
  // // end of inventory
  // inputText: {
  //   marginTop: 4,
  //   padding: 10,
  //   fontFamily: "regular",
  //   paddingHorizontal: 15,
  //   marginBottom: 10,
  //   borderRadius: 8,
  //   width: "100%",
  //   borderColor: colors.gray,
  //   borderWidth: 1,
  // },
  // label: {
  //   fontFamily: "regular",
  //   marginBottom: 4,
  // },
  // imageUploadText: {
  //   fontSize: 17,
  //   fontFamily: "semibold",
  //   color: colors.gray,
  // },
  // // end of product form
  // // end of search
  // viewProductHeader: {
  //   alignItems: "center",
  //   flexDirection: "row",
  // },
  // viewProductButton: {
  //   padding: 5,
  //   // backgroundColor: "red",
  //   marginHorizontal: 2,
  // },
  // regular: {
  //   fontFamily: "regular",
  // },

  loadingText: {
    padding: 8,
    fontSize: 12,
    fontFamily: "semibold",
    textAlign: "center",
    marginBottom: 20,
  },
  loadingContent: {
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    aspectRatio: 1 / 1,
    padding: 10,
  },
  loadingWrapper: {
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 5,
    width: "100%",
    backgroundColor: "rgba(255,255,255,1)",
  },
  syncBtn: {
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1,
    position: "absolute",
    right: 20,
    bottom: 20,
    width: 50,
    height: 50,
    borderRadius: 200,
    backgroundColor: colors.black,
  },
};
